<?php

use Illuminate\Database\Seeder;

class ProductDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_details')->delete();
        
        \DB::table('product_details')->insert(array (
            0 => 
            array (
                'id' => 9,
                'cpu' => 'Exynos 8890, 8 Nhân',
                'ram' => '4G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'Mali-T880 MP12',
                'storage' => '32 GB',
            'exten_memmory' => 'MicroSD (T-Flash)',
                'cam1' => '12MP',
                'cam2' => '5 MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3000mAh',
                'os' => 'Andoid 6.0',
                'note' => '',
                'pro_id' => 22,
                'created_at' => '2016-11-24 09:39:13',
                'updated_at' => '2016-11-28 18:02:19',
            ),
            1 => 
            array (
                'id' => 10,
                'cpu' => 'Exynos 8890, 8 Nhân',
                'ram' => '4G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'Mali-T880 MP12',
                'storage' => '32 GB',
            'exten_memmory' => 'MicroSD (T-Flash)',
                'cam1' => '12MP',
                'cam2' => '5 MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3000mAh',
                'os' => 'Andoid 6.0',
                'note' => '',
                'pro_id' => 23,
                'created_at' => '2016-11-24 09:39:28',
                'updated_at' => '2016-11-24 09:39:28',
            ),
            2 => 
            array (
                'id' => 11,
                'cpu' => 'Apple A10',
                'ram' => '3G',
            'screen' => '5.5 inch (1920 x 1080 pixels)',
                'vga' => 'chip apple 6 nhân',
                'storage' => '256 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Nano',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, Linning',
                'pin' => '2890mAh',
                'os' => 'IOS 10.0',
                'note' => '',
                'pro_id' => 24,
                'created_at' => '2016-11-24 18:48:39',
                'updated_at' => '2016-12-01 20:52:21',
            ),
            3 => 
            array (
                'id' => 12,
                'cpu' => 'Apple A10',
                'ram' => '3G',
            'screen' => '5.5 inch (1920 x 1080 pixels)',
                'vga' => 'chip apple 6 nhân',
                'storage' => '128 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Nano',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, Linning',
                'pin' => '2890mAh',
                'os' => 'IOS 10.0',
                'note' => '',
                'pro_id' => 25,
                'created_at' => '2016-11-24 18:48:46',
                'updated_at' => '2016-12-01 20:53:36',
            ),
            4 => 
            array (
                'id' => 13,
                'cpu' => 'snapdragon 821 2.5 Ghz',
                'ram' => '6G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'adreno900',
                'storage' => '128 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3500mAh',
                'os' => 'Andoid 7.0',
                'note' => '',
                'pro_id' => 26,
                'created_at' => '2016-11-25 23:44:07',
                'updated_at' => '2016-11-28 23:01:37',
            ),
            5 => 
            array (
                'id' => 14,
                'cpu' => 'snapdragon 821 2.5 Ghz',
                'ram' => '6G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'adreno900',
                'storage' => '128 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3500mAh',
                'os' => 'Andoid 7.0',
                'note' => '',
                'pro_id' => 27,
                'created_at' => '2016-11-25 23:44:11',
                'updated_at' => '2016-11-28 23:01:52',
            ),
            6 => 
            array (
                'id' => 15,
                'cpu' => 'snapdragon 821 2.5 Ghz',
                'ram' => '6G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'adreno900',
                'storage' => '128 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3500mAh',
                'os' => 'Andoid 7.0',
                'note' => '',
                'pro_id' => 28,
                'created_at' => '2016-11-25 23:44:15',
                'updated_at' => '2016-11-28 23:02:04',
            ),
            7 => 
            array (
                'id' => 21,
                'cpu' => 'snapdragon 821 2.5 Ghz',
                'ram' => '6G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'adreno900',
                'storage' => '128 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3500mAh',
                'os' => 'Andoid 7.0',
                'note' => '',
                'pro_id' => 34,
                'created_at' => '2016-11-25 23:45:03',
                'updated_at' => '2016-11-28 23:03:32',
            ),
            8 => 
            array (
                'id' => 22,
                'cpu' => 'snapdragon 821 2.5 Ghz',
                'ram' => '6G',
            'screen' => '5.1 inch (1440 x 2560 pixels)',
                'vga' => 'adreno900',
                'storage' => '128 G',
                'exten_memmory' => 'không',
                'cam1' => 'dual 12 MP',
                'cam2' => '7MP',
                'sim' => '1 Sim Micro',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '3500mAh',
                'os' => 'Andoid 7.0',
                'note' => '',
                'pro_id' => 35,
                'created_at' => '2016-11-25 23:45:08',
                'updated_at' => '2016-11-28 23:04:05',
            ),
            9 => 
            array (
                'id' => 23,
                'cpu' => 'Intel, Celeron, N3050, 1.60 GHz',
            'ram' => '	DDR3L (1 khe RAM), 2 GB, 1600 MHz',
            'screen' => '15.6 inch, HD (1366 x 768 pixels)',
            'vga' => 'Intel® HD Graphics, Share (Dùng chung bộ nhớ với RAM)',
                'storage' => 'HDD, 500 GB',
                'exten_memmory' => 'có',
            'cam1' => '0.9 MP(16:9)',
                'cam2' => '',
                'sim' => 'không',
                'connect' => '802.11b/g/n, Bluetooth v4.0',
                'pin' => 'Li-Ion 4 cell',
                'os' => 'Windows 10 bản dùng thử',
                'note' => '',
                'pro_id' => 36,
                'created_at' => '2016-11-26 00:43:40',
                'updated_at' => '2016-11-26 00:43:40',
            ),
            10 => 
            array (
                'id' => 24,
                'cpu' => 'Intel, Celeron, N3050, 1.60 GHz',
            'ram' => '	DDR3L (1 khe RAM), 2 GB, 1600 MHz',
            'screen' => '15.6 inch, HD (1366 x 768 pixels)',
            'vga' => 'Intel® HD Graphics, Share (Dùng chung bộ nhớ với RAM)',
                'storage' => 'HDD, 500 GB',
                'exten_memmory' => 'có',
            'cam1' => '0.9 MP(16:9)',
                'cam2' => '',
                'sim' => 'không',
                'connect' => '802.11b/g/n, Bluetooth v4.0',
                'pin' => 'Li-Ion 4 cell',
                'os' => 'Windows 10 bản dùng thử',
                'note' => '',
                'pro_id' => 37,
                'created_at' => '2016-11-26 00:43:47',
                'updated_at' => '2016-11-26 00:43:47',
            ),
            11 => 
            array (
                'id' => 25,
                'cpu' => 'Intel, Celeron, N3050, 1.60 GHz',
            'ram' => '	DDR3L (1 khe RAM), 2 GB, 1600 MHz',
            'screen' => '15.6 inch, HD (1366 x 768 pixels)',
            'vga' => 'Intel® HD Graphics, Share (Dùng chung bộ nhớ với RAM)',
                'storage' => 'HDD, 500 GB',
                'exten_memmory' => 'có',
            'cam1' => '0.9 MP(16:9)',
                'cam2' => '',
                'sim' => 'không',
                'connect' => '802.11b/g/n, Bluetooth v4.0',
                'pin' => 'Li-Ion 4 cell',
                'os' => 'Windows 10 bản dùng thử',
                'note' => '',
                'pro_id' => 38,
                'created_at' => '2016-11-26 00:43:51',
                'updated_at' => '2016-11-26 00:43:51',
            ),
            12 => 
            array (
                'id' => 26,
                'cpu' => 'Intel, Celeron, N3050, 1.60 GHz',
            'ram' => '	DDR3L (1 khe RAM), 2 GB, 1600 MHz',
            'screen' => '15.6 inch, HD (1366 x 768 pixels)',
            'vga' => 'Intel® HD Graphics, Share (Dùng chung bộ nhớ với RAM)',
                'storage' => 'HDD, 500 GB',
                'exten_memmory' => 'có',
            'cam1' => '0.9 MP(16:9)',
                'cam2' => '',
                'sim' => 'không',
                'connect' => '802.11b/g/n, Bluetooth v4.0',
                'pin' => 'Li-Ion 4 cell',
                'os' => 'Windows 10 bản dùng thử',
                'note' => '',
                'pro_id' => 39,
                'created_at' => '2016-11-26 00:43:55',
                'updated_at' => '2016-11-26 00:43:55',
            ),
            13 => 
            array (
                'id' => 27,
                'cpu' => 'Intel, Celeron, N3050, 1.60 GHz',
            'ram' => '	DDR3L (1 khe RAM), 2 GB, 1600 MHz',
            'screen' => '15.6 inch, HD (1366 x 768 pixels)',
            'vga' => 'Intel® HD Graphics, Share (Dùng chung bộ nhớ với RAM)',
                'storage' => 'HDD, 500 GB',
                'exten_memmory' => 'có',
            'cam1' => '0.9 MP(16:9)',
                'cam2' => '',
                'sim' => 'không',
                'connect' => '802.11b/g/n, Bluetooth v4.0',
                'pin' => 'Li-Ion 4 cell',
                'os' => 'Windows 10 bản dùng thử',
                'note' => '',
                'pro_id' => 40,
                'created_at' => '2016-11-26 00:43:58',
                'updated_at' => '2016-11-26 00:43:58',
            ),
            14 => 
            array (
                'id' => 28,
                'cpu' => 'Intel, Celeron, N3050, 1.60 GHz',
            'ram' => '	DDR3L (1 khe RAM), 2 GB, 1600 MHz',
            'screen' => '15.6 inch, HD (1366 x 768 pixels)',
            'vga' => 'Intel® HD Graphics, Share (Dùng chung bộ nhớ với RAM)',
                'storage' => 'HDD, 500 GB',
                'exten_memmory' => 'có',
            'cam1' => '0.9 MP(16:9)',
                'cam2' => '',
                'sim' => 'không',
                'connect' => '802.11b/g/n, Bluetooth v4.0',
                'pin' => 'Li-Ion 4 cell',
                'os' => 'Windows 10 bản dùng thử',
                'note' => '',
                'pro_id' => 41,
                'created_at' => '2016-11-26 00:44:02',
                'updated_at' => '2016-11-26 00:44:02',
            ),
            15 => 
            array (
                'id' => 29,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 42,
                'created_at' => '2016-11-26 02:13:19',
                'updated_at' => '2016-11-26 02:13:19',
            ),
            16 => 
            array (
                'id' => 30,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 43,
                'created_at' => '2016-11-26 02:13:24',
                'updated_at' => '2016-11-26 02:13:24',
            ),
            17 => 
            array (
                'id' => 31,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'Case thường',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 44,
                'created_at' => '2016-11-26 02:13:27',
                'updated_at' => '2016-11-26 02:13:27',
            ),
            18 => 
            array (
                'id' => 32,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 45,
                'created_at' => '2016-11-26 02:13:31',
                'updated_at' => '2016-11-26 02:13:31',
            ),
            19 => 
            array (
                'id' => 33,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 46,
                'created_at' => '2016-11-26 02:13:35',
                'updated_at' => '2016-11-26 02:13:35',
            ),
            20 => 
            array (
                'id' => 34,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 47,
                'created_at' => '2016-11-26 02:13:53',
                'updated_at' => '2016-11-26 02:13:53',
            ),
            21 => 
            array (
                'id' => 35,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 48,
                'created_at' => '2016-11-26 02:13:55',
                'updated_at' => '2016-11-26 02:13:55',
            ),
            22 => 
            array (
                'id' => 36,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 49,
                'created_at' => '2016-11-26 02:14:00',
                'updated_at' => '2016-11-26 02:14:00',
            ),
            23 => 
            array (
                'id' => 37,
                'cpu' => 'Core i5 650 3.2 Ghz/ Cache 4M/ 2.5 GT/s ',
            'ram' => 'DDRam3 Dual Channel 4GB bus 1333 (2GB x 2)',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'Intel® HD Graphics',
                'storage' => '250GB SATA 7200 rpm ',
                'exten_memmory' => 'không',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'USB, VGA, COM, Display Port ',
                'pin' => '',
                'os' => 'Cài sẵn Windows 7 bản quyền',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 50,
                'created_at' => '2016-11-26 02:14:03',
                'updated_at' => '2016-11-26 02:14:03',
            ),
            24 => 
            array (
                'id' => 38,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 51,
                'created_at' => '2016-11-26 02:18:03',
                'updated_at' => '2016-11-26 02:18:03',
            ),
            25 => 
            array (
                'id' => 39,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 52,
                'created_at' => '2016-11-26 02:18:08',
                'updated_at' => '2016-11-26 02:18:08',
            ),
            26 => 
            array (
                'id' => 40,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 53,
                'created_at' => '2016-11-26 02:18:11',
                'updated_at' => '2016-11-26 02:18:11',
            ),
            27 => 
            array (
                'id' => 41,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 54,
                'created_at' => '2016-11-26 02:18:14',
                'updated_at' => '2016-11-26 02:18:14',
            ),
            28 => 
            array (
                'id' => 42,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 55,
                'created_at' => '2016-11-26 02:18:17',
                'updated_at' => '2016-11-26 02:18:17',
            ),
            29 => 
            array (
                'id' => 43,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 56,
                'created_at' => '2016-11-26 02:18:34',
                'updated_at' => '2016-11-26 02:18:34',
            ),
            30 => 
            array (
                'id' => 44,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 57,
                'created_at' => '2016-11-26 02:19:12',
                'updated_at' => '2016-11-26 02:19:12',
            ),
            31 => 
            array (
                'id' => 45,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 58,
                'created_at' => '2016-11-26 02:19:16',
                'updated_at' => '2016-11-26 02:19:16',
            ),
            32 => 
            array (
                'id' => 46,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 59,
                'created_at' => '2016-11-26 02:19:19',
                'updated_at' => '2016-11-26 02:19:19',
            ),
            33 => 
            array (
                'id' => 47,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 60,
                'created_at' => '2016-11-26 02:20:26',
                'updated_at' => '2016-11-26 02:20:26',
            ),
            34 => 
            array (
                'id' => 48,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 61,
                'created_at' => '2016-11-26 02:20:32',
                'updated_at' => '2016-11-26 02:20:32',
            ),
            35 => 
            array (
                'id' => 49,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 62,
                'created_at' => '2016-11-26 02:20:35',
                'updated_at' => '2016-11-26 02:20:35',
            ),
            36 => 
            array (
                'id' => 50,
                'cpu' => 'Intel core I5 6300HQ',
                'ram' => '8G DDR4 2100',
                'screen' => 'Gigabyte H81-DS2',
                'vga' => 'GTX 950M 4G GDDR4',
                'storage' => '1T HDD, 128G SSD',
                'exten_memmory' => '',
                'cam1' => 'Intel FAN Chuẩn',
                'cam2' => 'CTS 350W',
                'sim' => '',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/ac, dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
                'pin' => '4Cel',
                'os' => 'Windows 10 bản dùng thử',
                'note' => 'Dây nguồn, Ốc ..',
                'pro_id' => 63,
                'created_at' => '2016-11-26 02:20:38',
                'updated_at' => '2016-11-26 02:20:38',
            ),
            37 => 
            array (
                'id' => 52,
                'cpu' => 'Intel Core i3 2100',
                'ram' => '4G DDR3',
                'screen' => 'ASUS H61-DS2',
                'vga' => 'Intel hd ',
                'storage' => '256 G HDD',
                'exten_memmory' => 'thường',
                'cam1' => 'INTEL FAN',
                'cam2' => '350W CTS',
                'sim' => 'Không có',
                'connect' => 'Wi-Fi 802.11 a/b/g/n/, LAN 1G',
                'pin' => 'Không có',
                'os' => 'WIN 7',
                'note' => 'Không có',
                'pro_id' => 69,
                'created_at' => '2016-11-28 18:10:45',
                'updated_at' => '2016-11-28 18:21:42',
            ),
        ));
        
        
    }
}